// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-knowledge-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-knowledge-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddKnowledge mocks base method.
func (m *MockRepo) AddKnowledge(arg0 []models.Knowledge) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKnowledge", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddKnowledge indicates an expected call of AddKnowledge.
func (mr *MockRepoMockRecorder) AddKnowledge(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKnowledge", reflect.TypeOf((*MockRepo)(nil).AddKnowledge), arg0)
}

// DescribeKnowledge mocks base method.
func (m *MockRepo) DescribeKnowledge(arg0 uint64) (*models.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeKnowledge", arg0)
	ret0, _ := ret[0].(*models.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeKnowledge indicates an expected call of DescribeKnowledge.
func (mr *MockRepoMockRecorder) DescribeKnowledge(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeKnowledge", reflect.TypeOf((*MockRepo)(nil).DescribeKnowledge), arg0)
}

// ListKnowledge mocks base method.
func (m *MockRepo) ListKnowledge(arg0, arg1 uint64) ([]models.Knowledge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKnowledge", arg0, arg1)
	ret0, _ := ret[0].([]models.Knowledge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKnowledge indicates an expected call of ListKnowledge.
func (mr *MockRepoMockRecorder) ListKnowledge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKnowledge", reflect.TypeOf((*MockRepo)(nil).ListKnowledge), arg0, arg1)
}
