// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/ocp-knowledge-api/ocp-knowledge-api.proto

package ocp_knowledge_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Knowledge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Topic  uint64 `protobuf:"varint,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Text   string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{0}
}

func (x *Knowledge) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Knowledge) GetTopic() uint64 {
	if x != nil {
		return x.Topic
	}
	return 0
}

func (x *Knowledge) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateKnowledgeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knowledge *Knowledge `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
}

func (x *CreateKnowledgeV1Request) Reset() {
	*x = CreateKnowledgeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeV1Request) ProtoMessage() {}

func (x *CreateKnowledgeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeV1Request.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKnowledgeV1Request) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

type CreateKnowledgeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *CreateKnowledgeV1Response) Reset() {
	*x = CreateKnowledgeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKnowledgeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeV1Response) ProtoMessage() {}

func (x *CreateKnowledgeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeV1Response.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKnowledgeV1Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeKnowledgeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DescribeKnowledgeV1Request) Reset() {
	*x = DescribeKnowledgeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeKnowledgeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeKnowledgeV1Request) ProtoMessage() {}

func (x *DescribeKnowledgeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeKnowledgeV1Request.ProtoReflect.Descriptor instead.
func (*DescribeKnowledgeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeKnowledgeV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DescribeKnowledgeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knowledge *Knowledge `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
}

func (x *DescribeKnowledgeV1Response) Reset() {
	*x = DescribeKnowledgeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeKnowledgeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeKnowledgeV1Response) ProtoMessage() {}

func (x *DescribeKnowledgeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeKnowledgeV1Response.ProtoReflect.Descriptor instead.
func (*DescribeKnowledgeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeKnowledgeV1Response) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

type ListKnowledgeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListKnowledgeV1Request) Reset() {
	*x = ListKnowledgeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeV1Request) ProtoMessage() {}

func (x *ListKnowledgeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeV1Request.ProtoReflect.Descriptor instead.
func (*ListKnowledgeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{5}
}

func (x *ListKnowledgeV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListKnowledgeV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListKnowledgeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Knowledge []*Knowledge `protobuf:"bytes,1,rep,name=knowledge,proto3" json:"knowledge,omitempty"`
}

func (x *ListKnowledgeV1Response) Reset() {
	*x = ListKnowledgeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKnowledgeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeV1Response) ProtoMessage() {}

func (x *ListKnowledgeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeV1Response.ProtoReflect.Descriptor instead.
func (*ListKnowledgeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListKnowledgeV1Response) GetKnowledge() []*Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

type RemoveKnowledgeV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveKnowledgeV1Request) Reset() {
	*x = RemoveKnowledgeV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveKnowledgeV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveKnowledgeV1Request) ProtoMessage() {}

func (x *RemoveKnowledgeV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveKnowledgeV1Request.ProtoReflect.Descriptor instead.
func (*RemoveKnowledgeV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveKnowledgeV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveKnowledgeV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRemoved bool `protobuf:"varint,1,opt,name=isRemoved,proto3" json:"isRemoved,omitempty"`
}

func (x *RemoveKnowledgeV1Response) Reset() {
	*x = RemoveKnowledgeV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveKnowledgeV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveKnowledgeV1Response) ProtoMessage() {}

func (x *RemoveKnowledgeV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveKnowledgeV1Response.ProtoReflect.Descriptor instead.
func (*RemoveKnowledgeV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveKnowledgeV1Response) GetIsRemoved() bool {
	if x != nil {
		return x.IsRemoved
	}
	return false
}

var File_api_ocp_knowledge_api_ocp_knowledge_api_proto protoreflect.FileDescriptor

var file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4d, 0x0a, 0x09, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22,
	0x56, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x09, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x09, 0x6b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x1a, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x59, 0x0a, 0x1b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4b, 0x6e,
	0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x52, 0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0x46, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3a, 0x0a, 0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x09, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x18,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56,
	0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x19, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x32, 0xbd, 0x04, 0x0a, 0x0f, 0x4f, 0x63, 0x70, 0x4b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x41, 0x70, 0x69, 0x12, 0x88, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x12, 0x2b, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12,
	0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x3a,
	0x01, 0x2a, 0x12, 0x90, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x12, 0x2d, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x7f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x6e, 0x6f, 0x77,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x8a, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x12, 0x2b, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x4b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x56, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a,
	0x12, 0x2f, 0x76, 0x31, 0x2f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f,
	0x63, 0x70, 0x2d, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x69,
	0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescOnce sync.Once
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescData = file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDesc
)

func file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescGZIP() []byte {
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescData)
	})
	return file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDescData
}

var file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ocp_knowledge_api_ocp_knowledge_api_proto_goTypes = []interface{}{
	(*Knowledge)(nil),                   // 0: ocp.knowledge.api.Knowledge
	(*CreateKnowledgeV1Request)(nil),    // 1: ocp.knowledge.api.CreateKnowledgeV1Request
	(*CreateKnowledgeV1Response)(nil),   // 2: ocp.knowledge.api.CreateKnowledgeV1Response
	(*DescribeKnowledgeV1Request)(nil),  // 3: ocp.knowledge.api.DescribeKnowledgeV1Request
	(*DescribeKnowledgeV1Response)(nil), // 4: ocp.knowledge.api.DescribeKnowledgeV1Response
	(*ListKnowledgeV1Request)(nil),      // 5: ocp.knowledge.api.ListKnowledgeV1Request
	(*ListKnowledgeV1Response)(nil),     // 6: ocp.knowledge.api.ListKnowledgeV1Response
	(*RemoveKnowledgeV1Request)(nil),    // 7: ocp.knowledge.api.RemoveKnowledgeV1Request
	(*RemoveKnowledgeV1Response)(nil),   // 8: ocp.knowledge.api.RemoveKnowledgeV1Response
}
var file_api_ocp_knowledge_api_ocp_knowledge_api_proto_depIdxs = []int32{
	0, // 0: ocp.knowledge.api.CreateKnowledgeV1Request.knowledge:type_name -> ocp.knowledge.api.Knowledge
	0, // 1: ocp.knowledge.api.DescribeKnowledgeV1Response.knowledge:type_name -> ocp.knowledge.api.Knowledge
	0, // 2: ocp.knowledge.api.ListKnowledgeV1Response.knowledge:type_name -> ocp.knowledge.api.Knowledge
	1, // 3: ocp.knowledge.api.OcpKnowledgeApi.CreateKnowledgeV1:input_type -> ocp.knowledge.api.CreateKnowledgeV1Request
	3, // 4: ocp.knowledge.api.OcpKnowledgeApi.DescribeKnowledgeV1:input_type -> ocp.knowledge.api.DescribeKnowledgeV1Request
	5, // 5: ocp.knowledge.api.OcpKnowledgeApi.ListKnowledgeV1:input_type -> ocp.knowledge.api.ListKnowledgeV1Request
	7, // 6: ocp.knowledge.api.OcpKnowledgeApi.RemoveKnowledgeV1:input_type -> ocp.knowledge.api.RemoveKnowledgeV1Request
	2, // 7: ocp.knowledge.api.OcpKnowledgeApi.CreateKnowledgeV1:output_type -> ocp.knowledge.api.CreateKnowledgeV1Response
	4, // 8: ocp.knowledge.api.OcpKnowledgeApi.DescribeKnowledgeV1:output_type -> ocp.knowledge.api.DescribeKnowledgeV1Response
	6, // 9: ocp.knowledge.api.OcpKnowledgeApi.ListKnowledgeV1:output_type -> ocp.knowledge.api.ListKnowledgeV1Response
	8, // 10: ocp.knowledge.api.OcpKnowledgeApi.RemoveKnowledgeV1:output_type -> ocp.knowledge.api.RemoveKnowledgeV1Response
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_ocp_knowledge_api_ocp_knowledge_api_proto_init() }
func file_api_ocp_knowledge_api_ocp_knowledge_api_proto_init() {
	if File_api_ocp_knowledge_api_ocp_knowledge_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Knowledge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnowledgeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKnowledgeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeKnowledgeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeKnowledgeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKnowledgeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKnowledgeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveKnowledgeV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveKnowledgeV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_knowledge_api_ocp_knowledge_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_knowledge_api_ocp_knowledge_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_knowledge_api_ocp_knowledge_api_proto_msgTypes,
	}.Build()
	File_api_ocp_knowledge_api_ocp_knowledge_api_proto = out.File
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_rawDesc = nil
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_goTypes = nil
	file_api_ocp_knowledge_api_ocp_knowledge_api_proto_depIdxs = nil
}
